package info.scce.cinco.product.fp.pcconfig.mb.html;

import de.jabc.cinco.meta.core.utils.EclipseFileUtils;
import de.jabc.cinco.meta.plugin.generator.runtime.IGenerator;
import de.jabc.cinco.meta.runtime.CincoRuntimeBaseClass;
import info.scce.cinco.product.fp.pcconfig.mb.mgl.mainboard.CPUNode;
import info.scce.cinco.product.fp.pcconfig.mb.mgl.mainboard.GPUNode;
import info.scce.cinco.product.fp.pcconfig.mb.mgl.mainboard.Mainboard;
import info.scce.cinco.product.fp.pcconfig.mb.mgl.mainboard.MainboardContainer;
import info.scce.cinco.product.fp.pcconfig.mb.mgl.mainboard.RAMNode;
import info.scce.cinco.product.fp.pcconfig.mb.mgl.mainboard.RAMSlot;
import java.util.List;
import java.util.function.Consumer;
import org.eclipse.core.resources.IFile;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.ListExtensions;

@SuppressWarnings("all")
public class MBHTML extends CincoRuntimeBaseClass implements IGenerator<Mainboard> {
  private String fileName;
  
  private float totalPrice = 0.0f;
  
  @Override
  public void generate(final Mainboard model, final IPath path, final IProgressMonitor arg2) {
    final String fullFileName = this._workspaceExtension.getFile(model).getName();
    this.fileName = fullFileName.substring(0, fullFileName.lastIndexOf("."));
    final IFile targetFile = this._workspaceExtension.getWorkspaceRoot().getFileForLocation(path.append((this.fileName + ".html")));
    EclipseFileUtils.writeToFile(targetFile, this.template(model));
  }
  
  private String template(final Mainboard model) {
    EList<MainboardContainer> _mainboardContainers = model.getMainboardContainers();
    for (final MainboardContainer mbContainer : _mainboardContainers) {
      {
        final MainboardContainer mbcontainer = mbContainer;
        final EList<CPUNode> cpus = mbcontainer.getCPUSlots().get(0).getCPUNodes();
        final EList<GPUNode> gpus = mbcontainer.getGPUSlots().get(0).getGPUNodes();
        final Function1<RAMSlot, RAMNode> _function = (RAMSlot it) -> {
          RAMNode _xifexpression = null;
          boolean _isEmpty = it.getRAMNodes().isEmpty();
          boolean _not = (!_isEmpty);
          if (_not) {
            _xifexpression = it.getRAMNodes().get(0);
          }
          return _xifexpression;
        };
        final List<RAMNode> rams = ListExtensions.<RAMSlot, RAMNode>map(mbcontainer.getRAMSlots(), _function);
        if (((cpus.isEmpty() || gpus.isEmpty()) || rams.isEmpty())) {
          throw new IllegalArgumentException("Please finish Modeling Mainboard and install a CPU, GPU and at least one RAM!");
        }
        this.calculate_totalPrice(mbContainer);
        return this.to_html(mbcontainer);
      }
    }
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    String _html_head = this.html_head();
    _builder.append(_html_head);
    _builder.newLineIfNotEmpty();
    _builder.append("<body>");
    _builder.newLine();
    _builder.append("<h1 id=\"page-title\">Mainboard Model Details</h1>");
    _builder.newLine();
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("</html> ");
    _builder.newLine();
    _builder.append(" ");
    _builder.newLine();
    return _builder.toString();
  }
  
  private String to_html(final MainboardContainer mbContainer) {
    final CPUNode cpu = mbContainer.getCPUSlots().get(0).getCPUNodes().get(0);
    final GPUNode gpu = mbContainer.getGPUSlots().get(0).getGPUNodes().get(0);
    final Function1<RAMSlot, RAMNode> _function = (RAMSlot it) -> {
      RAMNode _xifexpression = null;
      boolean _isEmpty = it.getRAMNodes().isEmpty();
      boolean _not = (!_isEmpty);
      if (_not) {
        _xifexpression = it.getRAMNodes().get(0);
      } else {
        _xifexpression = null;
      }
      return _xifexpression;
    };
    final List<RAMNode> rams = ListExtensions.<RAMSlot, RAMNode>map(mbContainer.getRAMSlots(), _function);
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    String _html_head = this.html_head();
    _builder.append(_html_head);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("<body>");
    _builder.newLine();
    _builder.newLine();
    _builder.append(" ");
    _builder.append("<h1 id=\"page-title\">Mainboard Model Details</h1>");
    _builder.newLine();
    _builder.newLine();
    _builder.append(" ");
    _builder.append("<div id=\"total-price-container\">");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("<h2>Total price</h2>");
    _builder.newLine();
    _builder.append("       ");
    _builder.append("<p id=\"total-price\"> ");
    _builder.append(this.totalPrice, "       ");
    _builder.append("</p>");
    _builder.newLineIfNotEmpty();
    _builder.append("  ");
    _builder.append("</div>       ");
    _builder.newLine();
    String _mainboard_to_html = this.mainboard_to_html(mbContainer, cpu, gpu, rams);
    _builder.append(_mainboard_to_html);
    _builder.newLineIfNotEmpty();
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("</html> ");
    _builder.newLine();
    _builder.newLine();
    return _builder.toString();
  }
  
  private String html_head() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.append("<!DOCTYPE html>");
    _builder.newLine();
    _builder.append("<html>");
    _builder.newLine();
    _builder.append("<head>");
    _builder.newLine();
    _builder.append("<title>Mainboard Details</title>");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("<style>");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("body {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("font-family: Arial, sans-serif;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("margin: 0;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("padding: 0;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("background-color: #f4f4f4;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("color: #333;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(".component {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("background-color: #fff;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("border: 1px solid #ddd;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("border-radius: 4px;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("padding: 20px;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("margin: 20px;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("box-shadow: 0 2px 4px rgba(0,0,0,0.1);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(".component h2 {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("color: #444;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(".component ul {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("list-style-type: none;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("padding: 0;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append(".component li {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("margin-bottom: 10px;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("table {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("width: 100%;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("border-collapse: collapse;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("margin-bottom: 20px;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("border: 2px solid #4D4D4D;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("th, td {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("padding: 8px;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("text-align: left;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("border-bottom: 1px solid #4D4D4D; ");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("th {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("background-color: #4CAF50;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("color: white;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("tr:nth-child(even) {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("background-color: #f2f2f2;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("tr:hover {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("background-color: #ddd;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("td, th {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("border-left: 1px solid #4D4D4D;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("th:first-child, td:first-child {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("border-left: none;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#page-title {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("text-align: center;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("color: #2F4F4F; ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("font-size: 36px; ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("margin-bottom: 30px; ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("padding: 10px;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("border-bottom: 2px solid #4D4D4D; ");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("max-width: 70%;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("margin-left: auto;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("margin-right: auto;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#total-price-container {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("text-align: center;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("background-color: #ffffff; /* Weißer Hintergrund für Kontrast */");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("padding: 20px;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("margin-top: 30px;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("border-radius: 10px; /* Abgerundete Ecken */");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("box-shadow: 0 4px 8px rgba(0, 0, 0, 0.15); /* Schatten für Tiefe */");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("width: 50%;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("margin-left: auto;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("margin-right: auto;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#total-price-container h2 {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("margin: 0;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("color: #2F4F4F;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("font-size: 24px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#total-price {");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("color: #E85D04; /* Lebendige Farbe für den Preis */");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("font-size: 23px;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("font-weight: bold;");
    _builder.newLine();
    _builder.append("\t    ");
    _builder.append("margin-top: 20px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append(" ");
    _builder.append("</style>");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("</head>");
    _builder.newLine();
    _builder.newLine();
    return _builder.toString();
  }
  
  private String mainboard_to_html(final MainboardContainer mbcontainer, final CPUNode cpu, final GPUNode gpu, final List<RAMNode> rams) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"component\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<h2>Mainboard</h2>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table> ");
    _builder.newLine();
    _builder.append("            ");
    String _html_mainboard = this.html_mainboard(mbcontainer);
    _builder.append(_html_mainboard, "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("</table> ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"component\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<h2>CPU</h2>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table> ");
    _builder.newLine();
    _builder.append("            ");
    String _html_cpu = this.html_cpu(cpu);
    _builder.append(_html_cpu, "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("</table> ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"component\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<h2>GPU</h2>");
    _builder.newLine();
    _builder.append("         ");
    _builder.append("<table> ");
    _builder.newLine();
    _builder.append("            ");
    String _html_gpu = this.html_gpu(gpu);
    _builder.append(_html_gpu, "            ");
    _builder.newLineIfNotEmpty();
    _builder.append("         ");
    _builder.append("</table> ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("<div class=\"component\">");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("<h2>RAMs</h2>");
    _builder.newLine();
    _builder.newLine();
    {
      for(final RAMNode ram : rams) {
        {
          boolean _notEquals = this._graphModelExtension.operator_notEquals(ram, null);
          if (_notEquals) {
            _builder.append("<div class=\"component\">");
            _builder.newLine();
            _builder.append("  ");
            _builder.append("<h3>RAM</h3>");
            _builder.newLine();
            _builder.append("  \t ");
            _builder.append("<table>");
            String _html_ram = this.html_ram(ram);
            _builder.append(_html_ram, "  \t ");
            _builder.append("</table>\t\t          \t ");
            _builder.newLineIfNotEmpty();
            _builder.append("</div>");
            _builder.newLine();
          }
        }
      }
    }
    _builder.append("</div>");
    return _builder.toString();
  }
  
  private String html_mainboard(final MainboardContainer mbContainer) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<tr><td>Name </td><td>");
    String _name = mbContainer.getName();
    _builder.append(_name);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td>Socket </td><td>");
    String _socket = mbContainer.getSocket();
    _builder.append(_socket);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td>Chipset: </td><td>");
    String _chipset = mbContainer.getChipset();
    _builder.append(_chipset);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td>Type Memory Slots </td><td>");
    String _typeMemorySlots = mbContainer.getTypeMemorySlots();
    _builder.append(_typeMemorySlots);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td>Number of Memory Slots </td><td>");
    int _numMemorySlots = mbContainer.getNumMemorySlots();
    _builder.append(_numMemorySlots);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td>Number of PCIe x16 Slots </td><td>");
    int _numPCIe16Slots = mbContainer.getNumPCIe16Slots();
    _builder.append(_numPCIe16Slots);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td>Number of Sata Ports </td><td>");
    int _numSataPorts = mbContainer.getNumSataPorts();
    _builder.append(_numSataPorts);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td>Power consumption </td><td>");
    int _powerConsumption = mbContainer.getPowerConsumption();
    _builder.append(_powerConsumption);
    _builder.append(" Watt</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td>Factor </td><td>");
    String _formFactor = mbContainer.getFormFactor();
    _builder.append(_formFactor);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td>price: </td><td>");
    float _price = mbContainer.getPrice();
    _builder.append(_price);
    _builder.append(" Euro</td></tr>");
    _builder.newLineIfNotEmpty();
    return _builder.toString();
  }
  
  private String html_cpu(final CPUNode cpu) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<tr><td> Name </td><td>");
    String _name = cpu.getName();
    _builder.append(_name);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td> Type </td><td>");
    String _cpuType = cpu.getCpuType();
    _builder.append(_cpuType);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td> Power Consumption </td><td>");
    int _powerConsumption = cpu.getPowerConsumption();
    _builder.append(_powerConsumption);
    _builder.append(" Watt</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td> Socket </td><td>");
    String _socket = cpu.getSocket();
    _builder.append(_socket);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td> price </td><td>");
    float _price = cpu.getPrice();
    _builder.append(_price);
    _builder.append(" Euro</td></tr>");
    _builder.newLineIfNotEmpty();
    return _builder.toString();
  }
  
  private String html_gpu(final GPUNode gpu) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<tr><td> Name </td><td>");
    String _name = gpu.getName();
    _builder.append(_name);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td> Chip </td><td>");
    String _chip = gpu.getChip();
    _builder.append(_chip);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td> Memory </td><td>");
    int _memory = gpu.getMemory();
    _builder.append(_memory);
    _builder.append(" GB</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td> Power consumption </td><td>");
    int _powerConsumption = gpu.getPowerConsumption();
    _builder.append(_powerConsumption);
    _builder.append(" Watt</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr><td> Price </td><td>");
    float _price = gpu.getPrice();
    _builder.append(_price);
    _builder.append(" Euro</td></tr>");
    _builder.newLineIfNotEmpty();
    return _builder.toString();
  }
  
  private String html_ram(final RAMNode ram) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<tr> <td> Name </td> <td> ");
    String _name = ram.getName();
    _builder.append(_name);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr> <td> Type </td><td>");
    String _ramType = ram.getRamType();
    _builder.append(_ramType);
    _builder.append("</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr> <td> Capacity </td><td>");
    int _capacity = ram.getCapacity();
    _builder.append(_capacity);
    _builder.append(" GB</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr> <td>Power consumption </td> <td>");
    int _powerConsumption = ram.getPowerConsumption();
    _builder.append(_powerConsumption);
    _builder.append(" Watt</td></tr>");
    _builder.newLineIfNotEmpty();
    _builder.append("<tr> <td> Price </td> <td>");
    float _price = ram.getPrice();
    _builder.append(_price);
    _builder.append(" Euro</td></tr>");
    _builder.newLineIfNotEmpty();
    return _builder.toString();
  }
  
  private void calculate_totalPrice(final MainboardContainer mbContainer) {
    this.totalPrice = 0;
    float _talPrice = this.totalPrice;
    float _price = mbContainer.getPrice();
    this.totalPrice = (_talPrice + _price);
    final Consumer<CPUNode> _function = (CPUNode it) -> {
      int _powerConsumption = it.getPowerConsumption();
      float _plus = (this.totalPrice + _powerConsumption);
      this.totalPrice = _plus;
    };
    mbContainer.getCPUSlots().get(0).getCPUNodes().forEach(_function);
    final Consumer<GPUNode> _function_1 = (GPUNode it) -> {
      float _price_1 = it.getPrice();
      float _plus = (this.totalPrice + _price_1);
      this.totalPrice = _plus;
    };
    mbContainer.getGPUSlots().get(0).getGPUNodes().forEach(_function_1);
    final Consumer<RAMSlot> _function_2 = (RAMSlot it) -> {
      boolean _isEmpty = it.getRAMNodes().isEmpty();
      boolean _not = (!_isEmpty);
      if (_not) {
        float _price_1 = it.getRAMNodes().get(0).getPrice();
        float _plus = (this.totalPrice + _price_1);
        this.totalPrice = _plus;
      }
    };
    mbContainer.getRAMSlots().forEach(_function_2);
  }
}
